name: Angular Frontend Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: texais/src/frontend/texais-frontend-latest

      - name: Run tests with coverage
        run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage
        working-directory: texais/src/frontend/texais-frontend-latest

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-coverage
          path: texais/src/frontend/texais-frontend-latest/coverage/
